using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Dbbackup
{
    public partial class DbBackup : Form
    {
        public DbBackup()
        {
            InitializeComponent();
        }

        private void btnDbbackup_Click(object sender, EventArgs e)
        {
            string strCmdText="";
            //KYC_DETAILS,
            strCmdText = @"/K exp iccs/dvision "; 
            strCmdText= strCmdText+ "tables=AC_SCHEDULE,ACC_BSHEET,ACC_HEAD,ACC_HEAD_MGR,ACC_HEAD_SGR,ADL_LOAN_DATA,BALANCE_SHEET,BANK_CASH_BALANCE,BANK_CHARGE,BANK_CHARGE_SBIPP,BANK_INV_BALNCE,BANK_MASTER,BP_MASTER,BRANCH_MAST,CANCELL_REGISTER,CASH_ACCOUNT,CASH_BOOK,CASH_DEPOSIT,CASTE_MAST,CB_BAL_SBIPP,CB_BALANCE,CB_PAGE,CLAIM_REGISTER,CLOSE_DATA_LOAN,CLW_EMP_MAST,CLW_EMP_MAST_ONE,CLWCCS,CMTD_LEDGER,CMTD_TAG,CON_DO,CON_PO,CONSTITUENCY,COUNTER_CASHIER,COUNTER_FIVE,COUNTER_FOUR,COUNTER_MAST,COUNTER_ONE,COUNTER_SIX,COUNTER_THREE,COUNTER_TWO,CUSTOMER,CUSTOMER_NOMINEE,CYCLE_ADVANCE,DA_RATE,DATE_POSTING,DEDUCT_ACHD_MAST,DELUX_H_LEDGER,DELUX_HH_LEDGER,DELUX_ROOM_RATE,DELUX_ROOM_TYPE,DENOM_MASTER,DENOM_MOVE_MAST,DENOM_POINT_MAST,DENOM_TRNDTL,DENOM_TRNHDR,DEP_DEMAND_INTSCDL,DEPOSIT_CHQBAR,DEPOSIT_CHQDTL,DEPOSIT_CHQHDR,DEPOSIT_CUSTOMER,DEPOSIT_DEBIT,DEPOSIT_INTMAST,DEPOSIT_INTR_MAST,DEPOSIT_INTRODUCER,DEPOSIT_LEDGER_FD,DEPOSIT_LEDGER_SB,DEPOSIT_LEDGER_TEMP,DEPOSIT_LEDGER_TEST,DEPOSIT_MAST,DEPOSIT_NOMINEE,DEPOSIT_OPRN_MAST,DEPOSIT_PASSBOOK,DEPOSIT_SPLSTAT_MAST,DEPOSIT_STATUS,DEPOSIT_STATUS_MASTER,DEPT_MAST,DEPTYPE_MAST,DESIG_MAST,DIV_PRIN,DIVIDEND_LEDGER,DORMANT,EMPLOYER_BRANCH_MAST,EMPLOYER_MAST,EXCESS_LOAN_REFUND,FASTIVAL_ADVANCE,FD_CERT_PRINT,FES_CANCELL,FIXED_DEPOSIT_LEDGER,FIXED_DEPOSITS,FLAT,FLAT1,FLAT2,FORM_IDMAST,FUNDDEP_MAST,GENERAL_LEDGER,GF_LEDGER,GIFT_ISSUE,GIFT_MASTER,GIFT_STOCK,GL_BALNCE,H_HEADER,H_LEDGER,HBA_RECOVERY_STAFF,HH_LEDGER,HH_LICENCE,HHOME_STATUS,IMPREST_CASH,IPASS_CONTNO,ISSUE_CHEQUE,ISSUE_CHEQUE_SBIPP,JOURNAL_BOOK,LEAVE_REG_CL,LEAVE_REG_LAHP,LEAVE_REG_LAP,LICENSEE,LIST_LOAN_LTL,LNAINTRATE_DTL,LNCATEGORY_MAST,LNCERT_TYPE,LNINTRATE_DTL,LNMRTG_TYPE_MAST,LNPURPOSE_MAST,LNPURPOSE_MAST_RBI,LNREPAY_SAL_MAST,LNSCHEME_AINT,LNSCHEME_INT,LNSECURITY,LNSECURITY_RBI,LNSTATUS_MAST,LNSTATUS_MGR,LNTYPE_MAST,LOAN_BANNER,LOAN_CUSTOMER,LOAN_DATA,LOAN_FORM_ISSUE,LOAN_LEDGER_CON,LOAN_LEDGER_FES,LOAN_LEDGER_LTL,LOAN_LEDGER_STL,LOAN_MASTER,LOAN_PAYMENT_MODE,LOAN_REC_REGISTER,LOAN_RECOVERY_STAFF,LOAN_SECURITY,LOAN_SURITY,LOAN_SURITY_CON,LOANEE_TYPE,LOGIN_DETAILS,MAIL_AREA_MAST,MEN_IPASS_MAST,MEN_TRANS,MEMBER_CLOS_TEMP,MEMBER_CUSTOMER,MEMBER_INTRODUCER,MEMBER_MAST,MEMBER_NOMINEE,MEMBERS_SETTLEMENT,MEMCATEGORY_MAST,MEMTYPE_MAST,MICROSOFTDTROPERTIES,MODULE_MAST,MONTH,MONTHLY_DEDUCTION,MONTHLY_DEDUCTIONS,NEFT_CHARGE,NEFT_TRANSACTION,NET_PROFIT,NO_CLAIM_REGISTER,NOMINATION_REG,OCCUP_MAST,PAID_UNPAID,PARAM_PL_APPR,PASSBOOK_PRINT_DETAIL,PL_ACCOUNT,PLA,PT_SLAB,REC_CHEQUE,REC_CHEQUE_SBIPP,REC_PAYABLE,RECO_SCHEDULE_PORT,RECOVERY_ADVICE,RECOVERY_FROM_STAFF,RECOVERY_GET,RECOVERY_SCHEDULE,RELIGION_MAST,RELN_MAST,REP_ACC_CASHACC,REP_ACC_CASHBOOK,REP_ACC_DAYBOOK,REP_ACC_GENLED,REP_ACC_JOURNAL,REP_ACC_TRIAL,REP_BALANCE_SHEET,REP_BS_ANNEX,REP_CASHBOOK,REP_DEP_STATUS,REP_LOAN_RECOVERY,REP_LOAN_STATUS,REP_PL_ANNEX,REP_PROFIT_LOSS,REP_SAL_DEDUCTION,REP_TD_INTSCDL,REPORT_RECOVERY,REQUEST_MAST,ROLL_DETAIL,ROLL_MAST,ROOM_RATE,ROOM_TYPE,RT_BALNCE,S102,SB_DORMANT,SBI_MIH,SBIPP,SD_TAG,SEQ_PARAM,SERV_STATUS_MAST,SETTLEMENT_STATUS,SHARE_LEDGER,SHIFT_MAST,SLOAN_PAYMENT_MODE,STAFF_PERSONAL_FILE,STAFF_REGISTER,STAFF_SALARY,SURITY_SEEN,TD_INTDETL,TEMP_CMTD_LEDGER,TEMP_DEPOSIT_LEDGER,TEMP_DEPOSIT_MAST,TEMP_DEPOSIT_PASSBOOK,TEMP_FLAT1,TEMP_LOAN_FORM_ISSUE,TEMP_LOAN_LEDGER,TEMP_MEMBER_MAST,TEMP_NEFT_TRANSACTION,TEMP_PASSBOOK_PRINT_DETAIL,TEMP_SHARE_LEDGER,TEMP_TVCH_DETAIL,TEMP_VCH_ENTRY,TF_LEDGER,TF_RATE,TVCH_DETAIL,TVCH_HEADER,UNPAID_DEPOSIT_LEDGER,USER_ACHDBAR,USER_AMTBAR,USER_HOURS,USER_LOG,USER_MAST,USER_NODES,USER_OTH,USER_OTHPRIV_MAST,USER_POLICY,USER_ROLL,USER_SPLCASH_TRMODE,USERS,VCH_CHEQUE,VCH_DETAIL,VCH_DETAIL_ONE,VCH_FACC_HEADER,VCH_HEADER,VCH_HEADER_ONE,VCH_TYPE,VCHL_DETAIL,VCHS_DETAIL,VOTER_LIST,ZONE_MAST file='E:\\ICCS" + DateTime.Now.ToString("dd/MM/yyyy").Replace("-", "").Replace("/", "") + ".dmp'";
            System.Diagnostics.Process.Start("CMD.exe", strCmdText);
        }
    }
}
